apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jekyll
  name: jekyll
spec:
  containers:
  - image: kodekloud/jekyll-serve
    name: jekyll
    volumeMounts:
      - name: site
        mounthPath: /site
    resources: {}
  initContainers:
  - image: kodekloud/jekyll 
    name: copy-jekyll-site
    command: ["jekyll", "new", "/site"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:

status: {}
