apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
